// Ilya Zeldner - Braude College - 2026
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"; // <--- Import this

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Classroom Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar /> {/* The Navigation Bar sits here! */}
        {/* The "children" is the changing part (Home, Admin, Login) */}
        {children}
      </body>
    </html>
  );
}
